---
- name: Pip installed
  apt:
    name: python3-pip
    state: present
- name: apt-transport-https installed
  apt:
    name: apt-transport-https
    state: present
- name: ca-certificates installed
  apt:
    name: ca-certificates
    state: present
- name: curl installed
  apt:
    name: curl
    state: present
- name: gnupg installed
  apt:
    name: gnupg
    state: present
- name: lsb-release installed
  apt:
    name: lsb-release
    state: present
- name: Docker - Repositories GPG Key - Downloaded
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /opt/docker-gpg-key
  register: gpg_key_download
- name: Docker - Repositories GPG Key - Installed
  shell: gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg /opt/docker-gpg-key
  when: gpg_key_download.changed
- name: Docker - Repository - Installed
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- name: Docker - Installed
  apt:
    name: "{{ packages  }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
- name: Docker - python lib - APT
  apt:
    name: python3-docker
    state: present
- name: Python library - Remove old version
  pip:
    name: docker-py
    state: absent
- name: Docker - python lib
  pip:
    name: docker
- name: Docker plugin - Install grafana/loki
  shell: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
  ignore_errors: True
- name: "User ({{ ansible_user }}) - Can run docker"
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker
    state: present
