---
- include_vars: 
    file: secrets.yml
- name: Promtail - Configuration - Directory exist
  file:
    path: /etc/promtail
    state: directory
- name: Promtail - Configuration - Copy file
  template:
    src: "{{ role_path }}/templates/promtail.yaml"
    dest: /etc/promtail/promtail.yml
- name: Unzip
  apt:
    name: unzip
    state: present
- name: Promtail - Download
  get_url:
    url: https://github.com/grafana/loki/releases/download/v2.2.1/promtail-linux-amd64.zip
    dest: /opt/promtail-linux-amd64.zip
  register: promtail_download
- name: Promtail - Extract
  unarchive:
    src: /opt/promtail-linux-amd64.zip
    dest: /opt
    remote_src: yes
  when: promtail_download.changed
- name: Promtail - Install
  copy:
    src: /opt/promtail-linux-amd64
    dest: /usr/local/bin/promtail
    mode: a+x
    remote_src: yes
  when: promtail_download.changed
- name: Install promtail service
  copy:
    src: "{{ role_path }}/files/promtail.service"
    dest: "/usr/lib/systemd/system/promtail.service"
- name: Promtail started and enabled
  systemd:
    name: promtail
    state: started
    enabled: yes