---
- name: Provision image
  hosts: default
  become: true
  tasks:
    - name: "System up to date"
      apt:
        upgrade: yes
        update_cache: yes
    - include_role:
        name: firewall
    - include_role:
        name: prometheus_node_exporter
    - include_role:
        name: promtail
    - include_role:
        name: reverse_proxy
    - name: Allow incoming traffic on port 80
      community.general.ufw:
        rule: allow
        port: "80"
        insert: 1
    - name: Allow incoming traffic on port 443
      community.general.ufw:
        rule: allow
        port: "443"
        insert: 1
    - name: Reload firewall
      community.general.ufw:
        state: reloaded
    - include_role:
        name: docker
    - include_role:
        name: evevulcan