---
- name: Check configuration existence
  stat:
    path: "/etc/nginx/conf.d/{{ conf_name }}"
  register: conf
- name: Copy nginx configuration
  template:
    src: "{{ local_path_to_conf }}/{{ conf_name }}"
    dest: "/etc/nginx/conf.d/{{ conf_name }}"
  register: nginx_config
- name: Test nginx configuration
  shell: nginx -t
  when: nginx_config.changed
- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
  when: nginx_config.changed