name: Pipeline
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - run: go test ./...
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    strategy:
      matrix:
        goos: [ linux, windows ]
        goarch: [ 386, amd64, arm, arm64 ]
    steps:
      - uses: actions/checkout@v2
      - run: go build -o eve-industry-${{ matrix.goos }}-${{ matrix.goarch }} ./...
        if: ${{ matrix.goos != 'windows' || matrix.goarch != 'arm64' }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}