name: Pipeline
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - run: go test ./...
  build-linux:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    strategy:
      matrix:
        goarch: [ 386, amd64, arm, arm64 ]
    steps:
      - uses: actions/checkout@v2
      - run: go build -o eve-industry-linux-${{ matrix.goarch }} ./...
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
      - uses: actions/upload-artifact@v2
        with:
          name: eve-industry-linux-${{ matrix.goarch }}
          path: eve-industry-linux-${{ matrix.goarch }}
          retention-days: 2
  build-windows:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    strategy:
      matrix:
        goarch: [ 386, amd64 ]
    steps:
      - uses: actions/checkout@v2
      - run: go build -o eve-industry-windows-${{ matrix.goarch }}.exe ./...
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
      - uses: actions/upload-artifact@v2
        with:
          name: eve-industry-windows-${{ matrix.goarch }}.exe
          path: eve-industry-windows-${{ matrix.goarch }}.exe
          retention-days: 2
  acceptance-test-linux:
    runs-on: windows-latest
    needs: build-linux
    strategy:
      matrix:
        goarch: [ amd64 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: eve-industry-linux-${{ matrix.goarch }}
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - run: go test --tags=acceptance ./...
        env:
          EXECUTABLE_PATH: eve-industry-linux-${{ matrix.goarch }}.exe
  acceptance-test-windows:
    runs-on: windows-latest
    needs: build-windows
    strategy:
      matrix:
        goarch: [ amd64 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: eve-industry-windows-${{ matrix.goarch }}.exe
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - run: go test --tags=acceptance ./...
        env:
          EXECUTABLE_PATH: eve-industry-windows-${{ matrix.goarch }}.exe
  release:
    runs-on: ubuntu-latest
    needs:
      - acceptance-test-linux
      - acceptance-test-windows
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
      - uses: actions/download-artifact@v2
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          files: eve-industry-**/*