name: Pipeline
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - run: go test ./...
  # See: https://github.community/t/how-to-share-matrix-between-jobs/128595/8
  load-build-infos:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    outputs:
      goos: ${{ steps.set-goos.outputs.goos }}
      goarch: ${{ steps.set-goarch.outputs.goarch }}
    steps:
      - uses: actions/checkout@v2
      - id: set-goos
        run: |
          TASKS=$(echo $(cat .github/workflows/goos.json) | sed 's/ //g' )
          echo "::set-output name=goos::$TASKS"
      - id: set-goarch
        run: |
          TASKS=$(echo $(cat .github/workflows/goarch.json) | sed 's/ //g' )
          echo "::set-output name=goarch::$TASKS"
  build:
    runs-on: ubuntu-latest
    needs: load-build-infos
    strategy:
      matrix:
        goos: ${{ fromJson(needs.load-build-infos.outputs.goos) }}
        goarch: ${{ fromJson(needs.load-build-infos.outputs.goarch) }}
    steps:
      - uses: actions/checkout@v2
      - run: go build -o eve-industry-${{ matrix.goos }}-${{ matrix.goarch }} ./...
        if: ${{ matrix.goos != 'windows' || matrix.goarch != 'arm64' }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - uses: actions/upload-artifact@v2
        with:
          name: eve-industry-${{ matrix.goos }}-${{ matrix.goarch }}
          path: eve-industry-${{ matrix.goos }}-${{ matrix.goarch }}
          retention-days: 5