---
- include_vars:
    file: secrets.yml
- name: Eve Industry - Run container
  community.docker.docker_container:
    name: evevulcan
    image: normegil/evevulcan:latest
    restart_policy: always
    ports:
      - "18080:18080"
    log_driver: loki
    log_options:
      loki-url: "https://prometheus:{{ prometheus_user_pass }}@loki.normegil.be/loki/api/v1/push"
- name: Eve Industry - Configure endpoint
  include_role:
    name: reverse_proxy_configure
  vars:
    local_path_to_conf: "{{ playbook_dir }}/files/reverse_proxy_conf/"
    conf_name: "evevulcan_local.conf"